---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

#- name: "Install Logstash Plugins"
#  shell: |
#    executable=/bin/bash
#    chdir=/opt/logstash
#    sudo bin/plugin install {{ item }}
#  with_items:
#    - logstash-output-elasticsearch_java

- name: Create Logstash configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - server.conf
  notify: restart logstash

- name: Ensure Logstash is started and enabled on boot.
  service: "name=logstash state=started enabled={{ logstash_enabled_on_boot }}"
